name: another test
run-name: Testing
on: [push]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -  run: echo "testing done by"
            -  run: echo "Matende and Alia"
